#!/usr/bin/env  bash
#set -x
###  a esay-to-use shell script to create a project with android tools
Usage()
{
    echo -e "Usage: `basename $0` [-n name] [-a activity] \n";
    exit 1;
}

if [ $# -ne 4 ]
then 
    Usage
fi
if  [ "$1" != "-n" ] || [ "$3" != "-a" ]
then 
    Usage
fi
#if  [ "$3" != "-a" ]
#then 
#    Usage
#fi

NAME=$2
ACT=$4

android -v create project  -n  $NAME -a $ACT -k top.itmp.hz -t 1 -v 1.3.0 -g -p  $NAME
